#!/bin/bash -l
#SBATCH --qos=debug
#SBATCH --nodes=4
#SBATCH --constraint=haswell
#SBATCH --time=00:10:00    
#SBATCH --job-name=test
#SBATCH --account=m3780


export PARFLOW_DIR=/global/project/projectdirs/parflow/cori-v3.7.0-11-gf70ce58-2021-09-02
# export PARFLOW_DIR=/global/project/projectdirs/parflow/cori-v3.9.0-2021-09-02
source $PARFLOW_DIR/setenv.sh

srun -n 256 $PARFLOW_DIR/bin/parflow test_run
