#!/bin/bash
#PBS -N icom_tests
#PBS -A UCSM0009
#PBS -q regular 
#PBS -m bae
#PBS -M dtijerina@princeton.edu
#PBS -l walltime=00:30:00 
#PBS -l select=5:mpiprocs=36
#PBS -j oe

#PBS -o log.oe

source /etc/profile.d/modules.sh
ml conda
conda activate parflow-npl

source /glade/u/home/tijerina/.parflow.3.11.bashrc

mpirun -np 180 $PARFLOW_DIR/bin/parflow icom
